# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=42),
        ),
    ]
