# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_auto_20170918_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user',
        ),
    ]
