# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0004_auto_20170918_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(default='/static/images/noprofile.jpg', max_length=200),
        ),
    ]
