# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0007_auto_20170918_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='/static/grumblr/images/noprofile.jpg', max_length=200),
        ),
    ]
