# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import grumblr.models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_auto_20170928_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, default='(000)000-0000', max_length=20, validators=[grumblr.models.tele_validate]),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=42),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, default='Welcome to my Grumblr page!', max_length=420),
        ),
    ]
