# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import grumblr.models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_auto_20170928_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, validators=[grumblr.models.tele_validate]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
