# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0013_auto_20170930_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/static/grumblr/images/noprofile.jpg', max_length=200, upload_to='profile-images'),
        ),
    ]
