# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0015_auto_20171001_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/media/grumblr/images/noprofile.jpg', upload_to='profile-images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
