# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0020_auto_20171016_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follower_set', to='grumblr.Profile'),
        ),
    ]
