# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0023_auto_20171016_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follower_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
